@startuml
'https://plantuml.com/component-diagram
!theme hacker

storage 4转3进水三通角阀
storage 3转2快插

'前三级
interface 3分外牙弯通_1
interface 3分外牙弯通_2
interface 3分外牙弯通_3
interface 3分外牙弯通_4
interface 3分外牙弯通_5
interface 3分外牙弯通_6

'泵
interface 3分外牙快接_1
interface 3分外牙快接_2

'RO
interface 3分外牙弯通
interface 2分外牙弯通
interface 3转2外牙弯通

'T33
interface 2分外牙快接_1
interface 2分外牙快接_2

'水压表
interface 2分内牙弯通

storage 2分流量调节阀
storage 2分Y三通
storage 2分三通
storage 2分侧T_1
storage 2分侧T_2
storage 2分侧T_3

storage 3转2侧T_1
storage 3转2侧T_2
storage 3转2侧T_3
storage 3分三通


'一级
冷水角阀 - 4转3进水三通角阀
4转3进水三通角阀 -> [减压阀]
3分外牙弯通_1 - [PP滤]
[PP滤] - 3分外牙弯通_2
[减压阀] -> 3分外牙弯通_1

'二级
3分外牙弯通_2 -> 3分外牙弯通_3
3分外牙弯通_3 - [CTO滤]
[CTO滤] - 3分外牙弯通_4
3分外牙弯通_4 -> 3分外牙弯通_5


3分外牙弯通_5 - [3级滤]
[3级滤] - 3分外牙弯通_6
3分外牙弯通_6 -> 3分三通


'泵+RO
3分三通 ---> [进水电磁阀]
进水电磁阀 -left-> 3分外牙快接_1
3分外牙快接_1 -left- [泵]
[泵] -left- 3分外牙快接_2
3分外牙快接_2 -left-> 3转2侧T_2
3转2侧T_2 -left- 3转2侧T_3
3转2侧T_3 -- 3分外牙弯通
3分外牙弯通 -- [RO滤]
3转2侧T_2 .up.> 2分内牙弯通
2分内牙弯通 .left. [水压表]
[RO滤] -left- 3转2外牙弯通

'纯水出口
3转2外牙弯通 .left.> 2分侧T_3
2分侧T_3 ..> [逆止阀1]
[逆止阀1] .left.> [高压开关]
[高压开关] .left.> 2分外牙快接_1
2分外牙快接_1 .left. [T33滤]
[T33滤] .left. 2分外牙快接_2
2分外牙快接_2 .left.> 纯水龙头

'水驱
2分侧T_3 .left.> [逆止阀2]
[逆止阀2] .left.> 2分三通
2分三通 .left.> [0.5G压力桶]
2分三通 .up.> 2分侧T_2
2分侧T_2 .left.> 纯水TDS探针
2分侧T_2 .up.> [逆止阀3]
[逆止阀3] .> 3转2侧T_3

'废水调节出口
[RO滤] . 2分外牙弯通
2分外牙弯通 .> 2分侧T_1
2分侧T_1 . [废水电磁阀]
[废水电磁阀] .up.> 2分Y三通
2分侧T_1 .up. 2分流量调节阀
2分流量调节阀 .> 2分Y三通
2分Y三通 .> 废水出口

'水槽出口
3分三通 -> 3转2侧T_1
3转2侧T_1 -> 3转2快插
3转2快插 - 净水龙头
3转2侧T_1 .up.> 原水TDS探针

@enduml
