@startuml
'https://plantuml.com/component-diagram
!theme hacker
storage 4转3内牙快接
storage 4转3外牙快接

interface 4转3外牙弯通_1
interface 4转3外牙弯通_2
interface 4转3外牙弯通_3
interface 4转3外牙弯通_4
interface 4转3外牙弯通_5
interface 4转3外牙弯通_6

interface 3转3外牙快接_1
interface 3转3外牙快接_2

interface 2转2内牙快接
storage 2转2侧T
storage 2分流量调节阀
storage 2分Y三通
storage 2分三通_1
storage 2分三通_2
storage 2分侧T_2
storage 2分侧T_3

interface 2转2外牙弯通
interface 2转3外牙弯通_2

interface 2转2外牙快接_1
interface 2转2外牙快接_2

storage 3转2侧T_1
storage 3转2侧T_2
storage 3转2侧T_3
storage 3分三通
storage 2转3快插

interface 3分T型外牙三通

'一级
冷水角阀 - 4转3内牙快接
4转3内牙快接 -> [减压阀]
4转3外牙弯通_1 - [PP滤]
[PP滤] - 4转3外牙弯通_2
[减压阀] -> 4转3外牙弯通_1
4转3外牙弯通_2 -> 3转2侧T_1

'二级
3转2侧T_1 .up.> [低压开关]
3转2侧T_1 -> 4转3外牙弯通_3
4转3外牙弯通_3 - [CTO滤]
[CTO滤] - 4转3外牙弯通_4
4转3外牙弯通_4 -> 4转3外牙弯通_5


4转3外牙弯通_5 - [3级滤]
[3级滤] - 4转3外牙弯通_6
4转3外牙弯通_6 -> 3分三通


'泵+RO
3分三通 ---> [进水电磁阀_1]
进水电磁阀_1 -left-> 3转3外牙快接_1
3转3外牙快接_1 -left- [400G泵]
[400G泵] -left- 3转3外牙快接_2
3转3外牙快接_2 -left-> 3转2侧T_3
3转2侧T_3 -left-> 3分T型外牙三通
3分T型外牙三通 -- [RO滤]
3转2侧T_3 .up.> 2转2内牙快接
2转2内牙快接 .left. [水压表]
[RO滤] -left- 2转3外牙弯通_2

'纯水出口
2转3外牙弯通_2 .left.> 2分侧T_3
2分侧T_3 ..> [逆止阀1]
[逆止阀1] .left.> [高压开关]
[高压开关] .left.> 2转2外牙快接_1
2转2外牙快接_1 .left. [T33滤]
[T33滤] .left. 2转2外牙快接_2
2转2外牙快接_2 .left.> 纯水龙头

'水驱
2分侧T_3 .left.> [逆止阀2]
[逆止阀2] .left.> 2分三通_2
2分三通_2 .left.> 2分内牙弯通
2分内牙弯通 .left. [0.5G压力桶]
2分三通_2 .up.> 2分侧T_2
2分侧T_2 .left.> 纯水TDS探针
2分侧T_2 .up.> [逆止阀3]
[逆止阀3] .> 2转3快插
2转3快插 - 3分T型外牙三通

'废水调节出口
[RO滤] . 2转2外牙弯通
2转2外牙弯通 .> 2转2侧T
2转2侧T . [进水电磁阀_2]
[进水电磁阀_2] .up.> 2分Y三通
2转2侧T .up. 2分流量调节阀
2分流量调节阀 .> 2分Y三通
2分Y三通 .> 废水出口

'水槽出口
3分三通 -> 3转2侧T_2
3转2侧T_2 -> 4转3外牙快接
4转3外牙快接 - 水槽水龙头
3转2侧T_2 .up.> 原水TDS探针

@enduml
